llm:
  openai:
    provider: "openai"
    model_name: "o4-mini"
  groq:
    provider: "groq"
    model_name: "openai/gpt-oss-120b"
  google_genai:
    provider: "google_genai"
    model_name: "gemini-2.5-flash"